const data= [
  {
    title: "Software Engineer",
    description: "Develop and maintain scalable web applications.",
    requirement: "Proficient in JavaScript, Node.js, and React.",
    location: { city: "New York", state: "NY", country: "USA" },
    listingtype: "job",
    openings: 3,
    salaryRange: { min: 80000, max: 120000 },
    jobType: "Full-time",
    owner:"68dfdca976ca6ecd2b35165b",
  },
  {
    title: "Marketing Manager",
    description: "Lead digital marketing campaigns and strategies.",
    requirement: "Experience in SEO, SEM, and social media marketing.",
    location: { city: "San Francisco", state: "CA", country: "USA" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 60000, max: 90000 },
    jobType: "Full-time",
    owner:"68dfdb5776ca6ecd2b35161c",
  },
  {
    title: "Data Analyst",
    description: "Analyze data trends and generate actionable insights.",
    requirement: "Strong skills in SQL, Excel, and data visualization.",
    location: { city: "Toronto", state: "ON", country: "Canada" } ,
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 45000, max: 70000 },
    jobType: "Full-time",
    owner:"68dfdb5776ca6ecd2b35161c",
  },
  {
    title: "Graphic Designer",
    description: "Create visually engaging graphics for digital media.",
    requirement: "Proficiency in Adobe Creative Suite.",
    location: { city: "London", state: "England", country: "UK" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 35000, max: 50000 },
    jobType: "Part-time",
    owner:"68dfdb7776ca6ecd2b351623",
  },
  {
    title: "Project Manager",
    description: "Oversee project planning and execution.",
    requirement: "Experience with Agile methodologies and team leadership.",
    location: { city: "Berlin", state: "Berlin", country: "Germany" } ,
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 90000, max: 130000 },
    jobType: "Full-time",
    owner:"68dfdb7776ca6ecd2b351623",
  },
  {
    title: "Customer Support Specialist",
    description: "Provide excellent support via phone and email.",
    requirement: "Strong communication and problem-solving skills.",
     location: { city: "Paris", state: "Île-de-France", country: "France" },
    listingtype: "job",
    openings: 4,
    salaryRange: { min: 30000, max: 40000 },
    jobType: "Contract",
    owner:"68dfdbb176ca6ecd2b351631",
  },
  {
    title: "UX/UI Designer",
    description: "Design intuitive interfaces and improve user experience.",
    requirement: "Experience with Sketch, Figma, or Adobe XD.",
    location: { city: "Tokyo", state: "Tokyo", country: "Japan" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 55000, max: 75000 },
    jobType: "Full-time",
    owner:"668dfdbb176ca6ecd2b351631",
  },
  {
    title: "Business Analyst",
    description: "Evaluate business processes and identify improvement opportunities.",
    requirement: "Strong analytical skills and proficiency with BI tools.",
    location: { city: "Sydney", state: "NSW", country: "Australia" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 60000, max: 85000 },
    jobType: "Full-time",
    owner:"68dfdb9a76ca6ecd2b35162a",
  },
  {
    title: "Sales Executive",
    description: "Drive sales growth by acquiring new clients.",
    requirement: "Excellent communication and negotiation skills.",
    location: { city: "Bangalore", state: "Karnataka", country: "India" },
    listingtype: "job",
    openings: 3,
    salaryRange: { min: 40000, max: 60000 },
    jobType: "Contract",
    owner:"68dfdb9a76ca6ecd2b35162a",
  },
  {
    title: "Operations Manager",
    description: "Manage daily operations and streamline processes.",
    requirement: "Strong leadership and organizational skills.",
    location: { city: "Singapore", state: "Central", country: "Singapore" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 70000, max: 95000 },
    jobType: "Full-time",
    owner:"68dfdbcd76ca6ecd2b351638",
  },
  {
    title: "Digital Marketing Specialist",
    description: "Execute and monitor digital marketing campaigns.",
    requirement: "Experience with digital analytics and marketing tools.",
    location: { city: "Dublin", state: "Leinster", country: "Ireland" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 45000, max: 65000 },
    jobType: "Part-time",
    owner:"68dfdbcd76ca6ecd2b351638",
  },
  {
    title: "Content Strategist",
    description: "Develop and implement content strategies for brand growth.",
    requirement: "Strong writing skills and creative thinking.",
    location: { city: "Amsterdam", state: "North Holland", country: "Netherlands" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 50000, max: 70000 },
    jobType: "Full-time",
    owner:"68dfdc0a76ca6ecd2b35163f",
  },
  {
    title: "HR Coordinator",
    description: "Support HR functions and facilitate recruitment processes.",
    requirement: "Familiarity with HR systems and excellent interpersonal skills.",
    location: { city: "Dubai", state: "Dubai", country: "UAE" } ,
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 35000, max: 50000 },
    jobType: "Full-time",
    owner:"68dfdc0a76ca6ecd2b35163f",
  },
  {
    title: "Quality Assurance Engineer",
    description: "Conduct software tests to ensure high product quality.",
    requirement: "Knowledge of test automation and manual testing practices.",
    location: { city: "São Paulo", state: "SP", country: "Brazil" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 55000, max: 75000 },
    jobType: "Full-time",
    owner:"68dfdc2e76ca6ecd2b351646",
  },
  {
    title: "Network Administrator",
    description: "Maintain and secure the company's network infrastructure.",
    requirement: "Experience with network setup, monitoring, and security protocols.",
    location: { city: "Mexico City", state: "CDMX", country: "Mexico" } ,
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 60000, max: 80000 },
    jobType: "Full-time",
    owner:"68dfdc2e76ca6ecd2b351646",
  },
  {
    title: "Business Development Associate",
    description: "Identify new business opportunities and foster client relationships.",
    requirement: "Energetic with prior sales or business development experience.",
    location: { city: "Cape Town", state: "Western Cape", country: "South Africa" } ,
    listingtype: "job",
    openings: 3,
    salaryRange: { min: 40000, max: 60000 },
    jobType: "Contract",
    owner:"68dfdc5676ca6ecd2b35164d",
  },
  {
    title: "IT Support Specialist",
    description: "Provide technical support and resolve hardware/software issues.",
    requirement: "Strong troubleshooting skills and familiarity with IT systems.",
    location: { city: "Stockholm", state: "Stockholm County", country: "Sweden" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 35000, max: 50000 },
    jobType: "Part-time",
    owner:"68dfdc5676ca6ecd2b35164d",
  },
  {
    title: "Content Writer",
    description: "Produce engaging content for blogs, websites, and social media.",
    requirement: "Excellent writing skills and a creative mindset.",
    location: { city: "Auckland", state: "Auckland", country: "New Zealand" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 30000, max: 45000 },
    jobType: "Contract",
    owner:"68dfdc8d76ca6ecd2b351654",
  },
  {
    title: "Operations Analyst",
    description: "Evaluate operational processes and propose improvements.",
    requirement: "Strong analytical skills and experience with process optimization.",
     location: { city: "Zurich", state: "Zurich", country: "Switzerland" },
    listingtype: "job",
    openings: 1,
    salaryRange: { min: 50000, max: 70000 },
    jobType: "Full-time",
    owner:"68dfdc8d76ca6ecd2b351654",
  },
  {
    title: "DevOps Engineer",
    description: "Manage deployment pipelines and ensure system reliability.",
    requirement: "Experience with AWS, Docker, and CI/CD tools.",
    location: { city: "Seoul", state: "Seoul", country: "South Korea" },
    listingtype: "job",
    openings: 2,
    salaryRange: { min: 75000, max: 100000 },
    jobType: "Full-time",
    owner:"68dfdca976ca6ecd2b35165b",
  }
];

module.exports=data;