let data=[
  {
    title: "Software Engineering Intern",
    description: "Join our dynamic team to develop scalable web applications.",
    requirement: "Basic knowledge of JavaScript, Node.js, and React.",
    location: { city: "Boston", state: "MA", country: "USA" },
    internshiptype: "paid",
    stipend: 1500,
    openings: 3,
    owner:"68dfdb5776ca6ecd2b35161c",
  },
  {
    title: "Marketing Intern",
    description: "Assist with digital marketing campaigns and social media outreach.",
    requirement: "Strong communication skills and familiarity with social media platforms.",
     location: { city: "Los Angeles", state: "CA", country: "USA" },
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdb5776ca6ecd2b35161c",
  },
  {
    title: "Data Science Intern",
    description: "Analyze large datasets and build predictive models.",
    requirement: "Experience with Python, SQL, and machine learning basics.",
    location: { city: "Los Angeles", state: "CA", country: "USA" },
    internshiptype: "paid",
    stipend: 2000,
    openings: 2,
    owner:"68dfdb5776ca6ecd2b35161c",
  },
  {
    title: "Content Writing Intern",
    description: "Create engaging blog posts and articles for our website.",
    requirement: "Excellent writing skills and attention to detail.",
     location: { city: "Montreal", state: "QC", country: "Canada" } ,
    internshiptype: "unpaid",
    stipend: 0,
    openings: 2,
    owner:"68dfdb7776ca6ecd2b351623",
  
  },
  {
    title: "Graphic Design Intern",
    description: "Design visual content for digital and print media.",
    requirement: "Proficiency in Photoshop, Illustrator, and a strong design sense.",
    location: { city: "Manchester", state: "England", country: "UK" },
    internshiptype: "paid",
    stipend: 1000,
    openings: 1,
    owner:"68dfdb7776ca6ecd2b351623",
  },
  {
    title: "Cybersecurity Intern",
    description: "Help secure our systems and identify vulnerabilities.",
    requirement: "Understanding of network security and ethical hacking basics.",
    location: { city: "Barcelona", state: "Catalonia", country: "Spain" },
    internshiptype: "paid",
    stipend: 1800,
    openings: 2,
    owner:"68dfdb9a76ca6ecd2b35162a"
  },
  {
    title: "HR Intern",
    description: "Assist in recruitment and employee engagement initiatives.",
    requirement: "Good interpersonal skills and basic HR knowledge.",
     location: { city: "Munich", state: "Bavaria", country: "Germany" } ,
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdb9a76ca6ecd2b35162a",
  },
  {
    title: "Finance Intern",
    description: "Support financial analysis and budgeting activities.",
    requirement: "Strong analytical skills and proficiency in Excel.",
     location: { city: "Rome", state: "Lazio", country: "Italy" } ,
    internshiptype: "paid",
    stipend: 1200,
    openings: 1,
    owner:"68dfdbb176ca6ecd2b351631",
  },
  {
    title: "AI Intern",
    description: "Contribute to AI projects through data analysis and model training.",
    requirement: "Experience with Python and machine learning frameworks.",
    location: { city: "Seoul", state: "Seoul", country: "South Korea" } ,
    internshiptype: "paid",
    stipend: 2500,
    openings: 2,
    owner:"68dfdbb176ca6ecd2b351631",
  },
  {
    title: "Full-Stack Intern",
    description: "Work on both front-end and back-end development tasks.",
    requirement: "Proficiency in HTML, CSS, JavaScript, and a backend language.",
     location: { city: "Shanghai", state: "Shanghai", country: "China" },
    internshiptype: "paid",
    stipend: 2000,
    openings: 3,
    owner:"68dfdbcd76ca6ecd2b351638",
  },
  {
    title: "Customer Support Intern",
    description: "Assist customers via email and chat support.",
    requirement: "Excellent communication skills and problem-solving mindset.",
    location: { city: "Mumbai", state: "Maharashtra", country: "India" },
    internshiptype: "unpaid",
    stipend: 0,
    openings: 2,
    owner:"68dfdbcd76ca6ecd2b351638",
  },
  {
    title: "Event Management Intern",
    description: "Help plan and coordinate company events.",
    requirement: "Strong organizational skills and experience in event planning.",
    location: { city: "Delhi", state: "Delhi", country: "India" },
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdc0a76ca6ecd2b35163f",
  },
  {
    title: "Machine Learning Intern",
    description: "Develop and fine-tune machine learning algorithms.",
    requirement: "Knowledge of Python, TensorFlow, and data processing.",
    location: { city: "Melbourne", state: "VIC", country: "Australia" },
    internshiptype: "paid",
    stipend: 2200,
    openings: 2,
    owner:"68dfdc0a76ca6ecd2b35163f",
  },
  {
    title: "Legal Intern",
    description: "Assist with legal research and documentation.",
    requirement: "Understanding of legal concepts and strong research skills.",
    location: { city: "Wellington", state: "Wellington", country: "New Zealand" } ,
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdc2e76ca6ecd2b351646",
  },
  {
    title: "E-commerce Intern",
    description: "Support online store operations and digital marketing.",
    requirement: "Basic understanding of e-commerce platforms and social media.",
    location: { city: "Lisbon", state: "Lisbon", country: "Portugal" },
    internshiptype: "paid",
    stipend: 1300,
    openings: 2,
    owner:"68dfdc2e76ca6ecd2b351646",
 
  },
  {
    title: "Mobile App Intern",
    description: "Assist in mobile application development and testing.",
    requirement: "Experience with Android or iOS development tools.",
    location: { city: "Copenhagen", state: "Capital Region", country: "Denmark" },
    internshiptype: "paid",
    stipend: 1600,
    openings: 1,
    owner:"68dfdc5676ca6ecd2b35164d",

  },
  {
    title: "Social Media Intern",
    description: "Manage and create content for social media channels.",
    requirement: "Familiarity with social networks and basic graphic design skills.",
     location: { city: "Istanbul", state: "Istanbul", country: "Turkey" },
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdc5676ca6ecd2b35164d",

  },
  {
    title: "Business Analyst Intern",
    description: "Analyze business processes and aid in strategic planning.",
    requirement: "Strong analytical skills and attention to detail.",
     location: { city: "Buenos Aires", state: "Buenos Aires", country: "Argentina" },
    internshiptype: "paid",
    stipend: 1400,
    openings: 2,
    owner:"68dfdc8d76ca6ecd2b351654",
  },
  {
    title: "Product Management Intern",
    description: "Work with product and design teams to develop strategies.",
    requirement: "Excellent communication and problem-solving skills.",
    location: { city: "Nairobi", state: "Nairobi County", country: "Kenya" },
    internshiptype: "paid",
    stipend: 1700,
    openings: 1,
    owner:"68dfdc8d76ca6ecd2b351654",
   
  },
  {
    title: "Research Intern",
    description: "Assist with academic or market research projects.",
    requirement: "Strong research skills and familiarity with data analysis.",
    location: { city: "Mumbai", state: "Maharashtra", country: "India" },
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"68dfdca976ca6ecd2b35165b",

  },
  {
    title: "R&D Intern",
    description: "Contribute to research and development efforts in our innovation lab.",
    requirement: "Creative thinking and basic understanding of research methodologies.",
    location: { city: "Mumbai", state: "Maharashtra", country: "India" },
    internshiptype: "paid",
    stipend: 1900,
    openings: 2,
    owner:"68dfdca976ca6ecd2b35165b",
  }
];


module.exports=data;
